In [19]:
#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
author ： duanxxnj@163.com
time : 2016-06-03-14-34

脊回归测试代码
这里需要先生成一个线性相关的设计矩阵X，再使用脊回归对其进行建模
脊回归中最重要的就是参数alpha的选择，本例显示了不同的alpha下
模型参数omega不同的结果

"""

print(__doc__)
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# 这里设计矩阵X是一个希尔伯特矩阵（Hilbert matrix）
# 其元素A（i,j）=1(i + j -1),i和j分别为其行标和列标
# 希尔伯特矩阵是一种数学变换矩阵，正定，且高度病态
# 即，任何一个元素发生一点变动，整个矩阵的行列式的值和逆矩阵都会发生巨大变化
# 这里设计矩阵是一个10x5的矩阵，即有10个样本，5个变量
X = 1. / (np.arange(1, 6) + np.arange(0, 10)[:, np.newaxis])
y = np.arange(10,20)
# y = np.ones(10)
print ('设计矩阵为：')
print (X)

# alpha 取值为10^（-10）到10^（-2）之间的连续的200个值
n_alphas = 200
alphas = np.logspace(-10, -2, n_alphas)
# print ('\n alpha的值为：')
# print (alphas)

# 初始化一个Ridge Regression
clf = linear_model.Ridge()  #fit_intercept=False

# 参数矩阵，即每一个alpha对于的参数所组成的矩阵
coefs = []
score = []
# intercepts=[]
# 根据不同的alpha训练出不同的模型参数
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
#     print('alpha:',clf.coef_)
#     print('intercept:',clf.intercept_)
    coefs.append(clf.coef_)
    score.append(clf.score(X, y))
#     intercepts.append(clf.intercept_)

#获得绘图句柄
# ax = plt.gca()
# # 参数中每一个维度使用一个颜色表示
# ax.set_color_cycle(['b', 'r', 'g', 'c', 'k'])

# # 绘制alpha和对应的参数之间的关系图
# ax.plot(alphas, coefs)
# ax.set_xscale('log')    #x轴使用对数表示
# ax.set_xlim(ax.get_xlim()[::-1])  # 将x轴反转，便于显示
# plt.grid()
# plt.xlabel('alpha')
# plt.ylabel('weights')
# plt.title('Ridge coefficients as a function of the regularization')
# plt.axis('tight')
# plt.show()

# intercept=plt.gca()
# intercept.set_color_cycle(['b'])
# intercept.plot(alphas, intercepts)
# intercept.set_xscale('log')    #x轴使用对数表示
# intercept.set_xlim(intercept.get_xlim()[::-1])  # 将x轴反转，便于显示
# plt.grid()
# plt.xlabel('alpha')
# plt.ylabel('intercept')
# plt.title('Ridge coefficients intercepts')
# plt.axis('tight')
# plt.show()

scoreplot=plt.gca()
scoreplot.set_color_cycle(['b'])
scoreplot.plot(alphas, score)
scoreplot.set_xscale('log')    #x轴使用对数表示
scoreplot.set_xlim(scoreplot.get_xlim()[::-1])  # 将x轴反转，便于显示
plt.grid()
plt.xlabel('alpha')
plt.ylabel('score')
plt.title('Ridge coefficients score')
plt.axis('tight')
plt.show()




author ： duanxxnj@163.com
time : 2016-06-03-14-34

脊回归测试代码
这里需要先生成一个线性相关的设计矩阵X，再使用脊回归对其进行建模
脊回归中最重要的就是参数alpha的选择，本例显示了不同的alpha下
模型参数omega不同的结果


Using matplotlib backend: Qt5Agg
设计矩阵为：
[[ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 0.5         0.33333333  0.25        0.2         0.16666667]
 [ 0.33333333  0.25        0.2         0.16666667  0.14285714]
 [ 0.25        0.2         0.16666667  0.14285714  0.125     ]
 [ 0.2         0.16666667  0.14285714  0.125       0.11111111]
 [ 0.16666667  0.14285714  0.125       0.11111111  0.1       ]
 [ 0.14285714  0.125       0.11111111  0.1         0.09090909]
 [ 0.125       0.11111111  0.1         0.09090909  0.08333333]
 [ 0.11111111  0.1         0.09090909  0.08333333  0.07692308]
 [ 0.1         0.09090909  0.08333333  0.07692308  0.07142857]]


C:\Users\Administrator\Anaconda3\lib\site-packages\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)


In [11]:
# weight=coefs[0]
weight=[1,1,1,1,1,1,1,1,1,1]
# weight.shape=(5,1)
#weight=np.transpose(weight)
clf.score(X, y,weight)   #, sample_weight=weight

0.89970705985721899

In [16]:
clf.get_params(deep=True)

{'alpha': 0.01,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': False,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

In [22]:
# 初始化一个Ridge Cross-Validation Regression
clf = linear_model.RidgeCV()   #fit_intercept=False

# 训练模型
clf.fit(X, y)

print ('alpha的数值 : ', clf.alpha_)
print ('参数的数值：', clf.coef_)

alpha的数值 :  0.1
参数的数值： [-4.10782032 -4.60216997 -3.80408554 -3.09188755 -2.54082523]


In [23]:
clf.score(X,y)

0.74324489503472224

In [ ]:
cross_validation