In [32]:
#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
author ： duanxxnj@163.com
time : 2016-06-03-14-34

脊回归测试代码
这里需要先生成一个线性相关的设计矩阵X，再使用脊回归对其进行建模
脊回归中最重要的就是参数alpha的选择，本例显示了不同的alpha下
模型参数omega不同的结果

"""

print(__doc__)
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# 这里设计矩阵X是一个希尔伯特矩阵（Hilbert matrix）
# 其元素A（i,j）=1(i + j -1),i和j分别为其行标和列标
# 希尔伯特矩阵是一种数学变换矩阵，正定，且高度病态
# 即，任何一个元素发生一点变动，整个矩阵的行列式的值和逆矩阵都会发生巨大变化
# 这里设计矩阵是一个10x5的矩阵，即有10个样本，5个变量
X = 1. / (np.arange(1, 6) + np.arange(0, 10)[:, np.newaxis])
y = np.arange(10,20)
# y = np.ones(10)
print ('设计矩阵为：')
print (X)

# alpha 取值为10^（-10）到10^（-2）之间的连续的200个值
n_alphas = 200
alphas = np.logspace(-10, -2, n_alphas)
# print ('\n alpha的值为：')
# print (alphas)

# 初始化一个Ridge Regression
clf = linear_model.Ridge()  #fit_intercept=False

# 参数矩阵，即每一个alpha对于的参数所组成的矩阵
coefs = []
score = []
intercepts=[]
# 根据不同的alpha训练出不同的模型参数
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
#     print('alpha:',clf.coef_)
#     print('intercept:',clf.intercept_)
    coefs.append(clf.coef_)
    score.append(clf.score(X, y))
    intercepts.append(clf.intercept_)


author ： duanxxnj@163.com
time : 2016-06-03-14-34

脊回归测试代码
这里需要先生成一个线性相关的设计矩阵X，再使用脊回归对其进行建模
脊回归中最重要的就是参数alpha的选择，本例显示了不同的alpha下
模型参数omega不同的结果


Using matplotlib backend: Qt5Agg
设计矩阵为：
[[ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 0.5         0.33333333  0.25        0.2         0.16666667]
 [ 0.33333333  0.25        0.2         0.16666667  0.14285714]
 [ 0.25        0.2         0.16666667  0.14285714  0.125     ]
 [ 0.2         0.16666667  0.14285714  0.125       0.11111111]
 [ 0.16666667  0.14285714  0.125       0.11111111  0.1       ]
 [ 0.14285714  0.125       0.11111111  0.1         0.09090909]
 [ 0.125       0.11111111  0.1         0.09090909  0.08333333]
 [ 0.11111111  0.1         0.09090909  0.08333333  0.07692308]
 [ 0.1         0.09090909  0.08333333  0.07692308  0.07142857]]


In [33]:
#获得绘图句柄
# ax = plt.gca()
# # 参数中每一个维度使用一个颜色表示
# ax.set_color_cycle(['b', 'r', 'g', 'c', 'k'])

# # 绘制alpha和对应的参数之间的关系图
# ax.plot(alphas, coefs)
# ax.set_xscale('log')    #x轴使用对数表示
# ax.set_xlim(ax.get_xlim()[::-1])  # 将x轴反转，便于显示
# plt.grid()
# plt.xlabel('alpha')
# plt.ylabel('weights')
# plt.title('Ridge coefficients as a function of the regularization')
# plt.axis('tight')
# plt.show()

# intercept=plt.gca()
# intercept.set_color_cycle(['b'])
# intercept.plot(alphas, intercepts)
# intercept.set_xscale('log')    #x轴使用对数表示
# intercept.set_xlim(intercept.get_xlim()[::-1])  # 将x轴反转，便于显示
# plt.grid()
# plt.xlabel('alpha')
# plt.ylabel('intercept')
# plt.title('Ridge coefficients intercepts')
# plt.axis('tight')
# plt.show()

# scoreplot=plt.gca()
# scoreplot.set_color_cycle(['b'])
# scoreplot.plot(alphas, score)
# scoreplot.set_xscale('log')    #x轴使用对数表示
# scoreplot.set_xlim(scoreplot.get_xlim()[::-1])  # 将x轴反转，便于显示
# plt.grid()
# plt.xlabel('alpha')
# plt.ylabel('score')
# plt.title('Ridge score')
# plt.axis('tight')
# plt.show()

plt.subplots_adjust(hspace=0.5)
ax=plt.subplot(211)
ax.plot(alphas,coefs,alphas,intercepts)
ax.set_xscale('log')    #x轴使用对数表示
ax.set_xlim(ax.get_xlim()[::-1])  # 将x轴反转，便于显示
plt.xlabel('alpha')
plt.ylabel('weights and intercept')
plt.title('Ridge coefficients as a function of the regularization ')           
plt.grid(True)
bx=plt.subplot(212)
bx.set_xscale('log')    #x轴使用对数表示
bx.plot(alphas,score)
bx.set_xlim(bx.get_xlim()[::-1])  # 将x轴反转，便于显示
plt.xlabel('alpha')
plt.ylabel('score')
plt.title('Ridge score')
plt.grid(True)
plt.show()

In [29]:
clf.get_params(deep=True)

{'alpha': 0.01,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': False,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

In [41]:
# 初始化一个Ridge Cross-Validation Regression
clf = linear_model.RidgeCV(alphas=alphas,store_cv_values=True,normalize=True)   #fit_intercept=False

# 训练模型
clf.fit(X, y)

print ('alpha的数值 : ', clf.alpha_)
print ('截距的数值 : ', clf.intercept_)
print ('参数的数值：', clf.coef_)
print ('score的数值：', clf.cv_values_)
print ('score的数值：', clf.score(X, y))

alpha的数值 :  1e-10
截距的数值 :  45.7022294427
参数的数值： [   -68.70067235   1730.42094157  -9563.50490829  17916.43788202
 -10617.4313782 ]
score的数值： [[  1.49048700e-06   1.81032916e-06   2.18419834e-06 ...,   1.37230908e-01
    8.27909073e-02   4.02407686e-02]
 [  2.69795894e-04   3.39692657e-04   4.22268355e-04 ...,   6.46343263e-01
    6.25722165e-01   6.03112092e-01]
 [  1.99436502e-04   2.92878951e-04   4.07724214e-04 ...,   4.76323861e-03
    2.95722354e-03   1.49521459e-03]
 ..., 
 [  3.50471183e-04   3.74468153e-04   4.00729026e-04 ...,   1.87433923e-03
    1.43236690e-03   1.02451650e-03]
 [  2.46384080e-04   2.53387544e-04   2.60935487e-04 ...,   1.80402553e-01
    1.88817571e-01   1.97867939e-01]
 [  2.29287378e-03   2.42760025e-03   2.57323956e-03 ...,   1.15686105e+00
    1.18522447e+00   1.21523768e+00]]
score的数值： 0.999989473263


In [40]:
clf.get_params(deep=True)
clf.cv_values_.shape

(10, 200)